#!/bin/bash

# Some steps were taken from: 
# https://github.com/ShirleyWISiu/LigTMap#installation

# 1. MOPAC2016
mkdir mopac && cd mopac && curl -O http://openmopac.net/MOPAC2016_for_Linux_64_bit.zip

# Steps are a mix from https://github.com/ShirleyWISiu/LigTMap#1-mopac2016
# and the Installation instructions.txt from the ZIP file
sudo mkdir -p /opt/mopac && sudo chmod 777 /opt/mopac
unzip -d /opt/mopac mopac/MOPAC2016_for_Linux_64_bit.zip
chmod +x /opt/mopac/MOPAC2016.exe
printf "\nalias mopac='/opt/mopac/MOPAC2016.exe'\n">>~/.bashrc
printf "export LD_LIBRARY_PATH=/opt/mopac:$LD_LIBRARY_PATH\n">>~/.bashrc
source ~/.bashrc

cd ..

# 2. Openbabel
# https://github.com/ShirleyWISiu/LigTMap#4-openbabel
sudo apt update && sudo apt upgrade -y
sudo apt install cmake -y
sudo apt install swig libxml2 libxml2-dev zlib1g zlib1g-dev libeigen3-dev libcairo2 libcairo2-dev libcairo-5c-dev libboost-mpi-python-dev libboost-python-dev python-dev-is-python3 python3-dev libpython3-dev python3-devpi-common -y
sudo apt install openbabel python3-openbabel

cd ../..

# 3. PSOVina
# https://github.com/ShirleyWISiu/LigTMap#9-psovina

# a) boost
mkdir boost && cd boost
# Download (MANUALLY, because uses redirects) and install boost-1.59.0.tar.gz 
# from https://sourceforge.net/projects/boost/files/boost/1.59.0/ if boost is not yet in your system.
tar vxfz boost_1_59_0.tar.gz && cd boost_1_59_0
./bootstrap.sh --prefix=$HOME/opt/boost-1.59.0
./b2 -j`nproc`
./b2 install
printf "\n\nLD_LIBRARY_PATH=$HOME/opt/boost-1.59.0/lib:$LD_LIBRARY_PATH\n">>~/.bashrc
source ~/.bashrc

cd ../..

# b) PSOVina
# Once your boost is in place, download (MANUALLY, same reason above) and install 
# psovina-2.0.tar.gz from https://sourceforge.net/projects/psovina/
mkdir psovina && cd psovina
tar vxfz psovina-2.0.tar.gz # && cd psovina-2.0
cd psovina-2.0/build/linux/release/
cp Makefile Makefile.bck
sed -i "s|BASE=/usr/local|BASE=$HOME/opt/boost-1.59.0|g" Makefile
make -j`nproc`
mkdir ~/opt/psovina-2.0
cp psovina psovina_split ~/opt/psovina-2.0
export PATH=$HOME/opt/psovina-2.0:$PATH

cd ../../../../..

# 4. MGLTools
# https://github.com/ShirleyWISiu/LigTMap#10-mgltools
mkdir mgltools && cd mgltools
#curl -O https://ccsb.scripps.edu/download/532/
# Download (MANUALLY, same reason above) 
tar xvfz mgltools_x86_64Linux2_1.5.7.tar_.gz
mv mgltools_x86_64Linux2_1.5.7 ~/opt
cd ~/opt/mgltools_x86_64Linux2_1.5.7
./install.sh

# 5. gsplit (for MacOS X only)
# https://github.com/ShirleyWISiu/LigTMap#11-gsplit-for-macos-x-only
#brew install coreutils  

# ***************************
# ***************************
# Clean all
# ***************************
# ***************************
rm -r boost
rm -r mgltools
rm -r mopac
rm -r psovina
